# logs go to "logs/log{version}.txt", do 20 questions for animals[version]
version: 0

animals:
  - ['Coyote', 'Rhinoceros beetle', 'Wolverine', 'Saiga antelope', 'Yak', 'Kiwi', 'Zebra', 'Golden jackal', 'Horseshoe crab', 'Sand cat']
  - ['European badger', 'Blue dragon sea slug', 'Cassowary', 'Electric eel', 'Flying fox', 'Giraffe', 'Hammerhead shark', 'Vicu√±a', 'Ibex', 'Aye-aye']
  - ['Scarlet macaw', 'Peregrine falcon', 'Wildebeest', 'Capybara', 'Sea otter', 'Leafcutter ant', 'African elephant', 'Rosy boa', 'Quetzal', 'Snowy owl']
  - ['Jerboa', 'Gharial', 'Albatross', 'Dhole', 'Kookaburra', 'Monarch butterfly', 'Uakari', 'Bottlenose dolphin', 'Platypus', 'Brown bear']

# model combinations (Q, A) on which to run games
model_names:
  - ["Qwen", "Qwen"]
#  - ["Qwen", "Llama"]
#  - ["Llama", "Qwen"]
#  - ["Llama", "Llama"]

# methods on which to run games
method_names:
#  - "naive"
#  - "split"
#  - "Entropy"
  - "EIG"

# hyperparameters for LLM calls, optimal question & belief generation, and answer filtering
batched_block_size: 50
generation_temperature_diverse: 1.3
generation_temperature_simple: 1.0
answer_temperature: 0.7
target_num_questions: 15
num_mc_samples: 15
max_num_samples: 50
min_num_samples: 15
threshold_rejection_probability: 0.2